image:https://travis-ci.org/FunThomas424242/honey-toggle-button.svg?branch=master["Build Status", link="https://travis-ci.org/FunThomas424242/honey-toggle-button"]
image:https://codecov.io/gh/FunThomas424242/honey-toggle-button/branch/master/graph/badge.svg["codecov", link="https://codecov.io/gh/FunThomas424242/honey-toggle-button"]

== honey-toggle-button
Beispiel für eine Webkomponente

=== Benutzung

==== Aktuelle Workarounds

Vor dem npm run e2e bitte die selenium nodes als container starten
[source,shell]
----
sudo dockerd
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome
----

.Chrome Linux Sandbox einrichten (alternative Methode nach: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox)
[source, shell]
....
# cd to the downloaded instance
cd <project-dir-path>/node_modules/puppeteer/.local-chromium/linux-<revision>/chrome-linux/
sudo chown root:root chrome_sandbox
sudo chmod 4755 chrome_sandbox
# copy sandbox executable to a shared location
sudo cp -p chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
# export CHROME_DEVEL_SANDBOX env variable
export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox
....



== Lessons learned

* import spec ist deprecated
  nicht mehr unterstützt von chrome: <link rel="import" href="xxx.html">
  https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports
* w3-html-include
  lädt nur die html Seite aber nicht die darin referenzierten Styles und Skripte
  https://www.w3schools.com/w3js/w3js_html_include.asp
  https://www.quanzhanketang.com/howto/howto_html_include.html
* im Constructor lässt sich der Shadow DOM noch modifizieren (weil er noch nicht existiert)
* Wenn der Shadow DOM in einem Lifecycle Step angelegt wird, lässt er sich nach Verlassen des Steps nicht mehr
  modifizieren, darum sollte man vorher prüfen ob der ShadowDOM bereits existiert
* Eine Elementsuche über den ShadowDOM im Construktor liefert stets null weil die Elemente im DOM erst nach der
  Ausführung des Konstruktors erreichbar sind - selbst wenn sie schon in den DOM eingehangen wurden.
* Daher eignet sich der Konstruktur nur um Defaults für Attribute zu setzen.
* Alles andere wie Hinzufügen von Eventhandlern und suchen von Elementen sollte im Connected Callback passieren.

== NPM Module

* https://www.npmjs.com/package/accessibility Hinzufügen von Text2Speech Features etc.

* https://www.npmjs.com/package/nav-ally ACC Test mit Klicks
  https://github.com/dervism/carparkjs/blob/master/package.json (Beispiel)
* https://www.npmjs.com/package/lighthouse-automatic Automatischer Test verschiedener URLs
* https://www.npmjs.com/package/axe-core ACC Tests statisch -> nach jedem Klick aufrufen
* https://www.npmjs.com/package/axe-webdriverjs Aufsatz auf Axe Core
* https://www.npmjs.com/package/lighthouse auch programmatisch nutzbar
  https://github.com/GoogleChrome/lighthouse/blob/HEAD/docs/readme.md#using-programmatically
* https://www.npmjs.com/package/@nutmeg/cli
* https://www.npmjs.com/package/accessibility-html-reporter -> statische Analyse von HTML Dateien

== Quellen im Neuland

* https://dev.to/bennypowers/lets-build-web-components-part-3-vanilla-components-4on3
* https://www.webcomponents.org/element/Juicy/imported-template
* https://developer.mozilla.org/en-US/docs/Web/Web_Components
* https://github.com/o-t-w/copypaste-webcomponent
* https://coherent-labs.com/posts/web-components/
* https://www.smashingmagazine.com/2018/07/reusable-components-custom-elements-shadow-dom-npm/
* https://starcounter.io/html-partialsincludes-webcomponents-way/
* https://www.codementor.io/ayushgupta/vanilla-js-web-components-chguq8goz
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API
* https://www.techlounge.io/node#episodes
* https://github.com/mdn/web-components-examples/tree/master/element-details
* https://dev.to/thepassle/web-components-from-zero-to-hero-4n4m
* https://dev.to/open-wc/testing-workflow-for-web-components-g73
* https://open-wc.org/testing/#automating-tests
* https://marmelab.com/blog/2018/02/22/accessibililty-testing-e2e.html
* https://github.com/dequelabs/axe-webdriverjs
* https://www.npmjs.com/package/wdio-webcomponents
* https://github.com/Morlack/wdio-webcomponents/blob/master/test/wdio/specs/main.spec.js
* https://robotninja.com/blog/introduction-using-selenium-docker-containers-end-end-testing/
* https://rominirani.com/docker-tutorial-series-part-8-linking-containers-69a4e5bf50fb
* https://docs.travis-ci.com/user/docker/
* https://jaxenter.de/einfuehrung-docker-tutorial-container-61528
* https://docs.docker.com/engine/api/v1.37/# (Docker REST API)



